import base64
import os
import shutil
import tempfile
from io import BytesIO

import gradio as gr
# Work around a Gradio schema parser bug in some envs where JSON Schema booleans
# appear in component API info and crash the homepage route.
try:
    import gradio_client.utils as _gradio_client_utils

    _orig_get_type = _gradio_client_utils.get_type
    _orig_inner = _gradio_client_utils._json_schema_to_python_type
    _orig_outer = _gradio_client_utils.json_schema_to_python_type

    def _safe_get_type(schema):
        if isinstance(schema, bool):
            return {}
        return _orig_get_type(schema)

    def _safe_inner(schema, defs):
        if isinstance(schema, bool):
            return 'Any'
        return _orig_inner(schema, defs)

    def _safe_outer(schema):
        if isinstance(schema, bool):
            return 'Any'
        return _orig_outer(schema)

    _gradio_client_utils.get_type = _safe_get_type
    _gradio_client_utils._json_schema_to_python_type = _safe_inner
    _gradio_client_utils.json_schema_to_python_type = _safe_outer
except Exception:
    pass

import numpy as np
import torch
import torchvision.transforms as transforms
from decord import VideoReader
from PIL import Image, ImageDraw, ImageFont
from transformers import AutoModel, AutoTokenizer

# Hugging Face Spaces 的 GPU 装饰器；本地部署时通常没有该运行时，使用空实现即可。
try:
    import spaces  # type: ignore
except ImportError:  # pragma: no cover

    class _SpacesStub:
        class GPU:
            def __init__(self, *args, **kwargs):
                pass

            def __call__(self, fn):
                return fn

    spaces = _SpacesStub()

title_markdown = ("""
<div style="display: flex; justify-content: flex-start; align-items: center; text-align: center;">
  <div style="margin-right: 20px; display: flex; align-items: center;">
    <a href="https://github.com/ShareGPT4Omni/ShareGPT4Video" style="text-decoration: none; display: flex; align-items: center;">
      <img src="https://raw.githubusercontent.com/ShareGPT4V/ShareGPT4V-Resources/master/images/share4video_tight.png" alt="ShareGPT4Video🚀" style="max-width: 120px; height: auto;">
    </a>
  </div>
  <div>
    <h1>ShareGPT4Video: Improving Video Understanding and Generation with Better Captions</h1>
    <h5 style="margin: 0;">If you like our project, please give us a star ✨ on Github for the latest update.</h5>
    <h5 style="margin: 0;"> <a href="https://sharegpt4video.github.io/">[Project Page]</a> <a href="https://github.com/ShareGPT4Omni/ShareGPT4Video">[Code]</a> <a href="https://arxiv.org/abs/2406.04325v1">[Paper]</a>
  </div>
</div>
""")

block_css = """
#buttons button {
    min-width: min(120px,100%);
}
"""

learn_more_markdown = ("""
### License
The service is a research preview intended for non-commercial use only, subject to the model [License](https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md) of LLaMA, [Terms of Use](https://openai.com/policies/terms-of-use) of the data generated by OpenAI, and [Privacy Practices](https://chrome.google.com/webstore/detail/sharegpt-share-your-chatg/daiacboceoaocpibfodeljbdfacokfjb) of ShareGPT. Please contact us if you find any potential violation.
""")


new_path = os.environ.get(
    "SHARECAPTIONER_MODEL_PATH", "Lin-Chen/ShareCaptioner-Video"
)
tokenizer = AutoTokenizer.from_pretrained(new_path, trust_remote_code=True)
model = AutoModel.from_pretrained(
    new_path, torch_dtype=torch.float16, trust_remote_code=True
).cuda().eval()
model.cuda()
model.tokenizer = tokenizer


def padding_336(b, pad=336):
    width, height = b.size
    tar = int(np.ceil(height / pad) * pad)
    top_padding = int((tar - height)/2)
    bottom_padding = tar - height - top_padding
    left_padding = 0
    right_padding = 0
    b = transforms.functional.pad(
        b, [left_padding, top_padding, right_padding, bottom_padding], fill=[255, 255, 255])

    return b


def HD_transform(img, hd_num=25):
    width, height = img.size
    trans = False
    if width < height:
        img = img.transpose(Image.TRANSPOSE)
        trans = True
        width, height = img.size
    ratio = (width / height)
    scale = 1
    while scale*np.ceil(scale/ratio) <= hd_num:
        scale += 1
    scale -= 1
    new_w = int(scale * 336)
    new_h = int(new_w / ratio)

    img = transforms.functional.resize(img, [new_h, new_w],)
    img = padding_336(img, 336)
    width, height = img.size
    if trans:
        img = img.transpose(Image.TRANSPOSE)

    return img


def get_seq_frames(total_num_frames, desired_num_frames, start=None, end=None):
    if start is None:
        assert end is None
        start, end = 0, total_num_frames
    print(f"{start=}, {end=}")
    desired_num_frames -= 2
    end = min(total_num_frames, end)
    start = max(start, 0)
    seg_size = float((end - start)) / desired_num_frames
    seq = [start]

    for i in range(desired_num_frames):
        s = int(np.round(seg_size * i))
        e = int(np.round(seg_size * (i + 1)))
        seq.append(min(int(start + (s + e) // 2), total_num_frames-1))
    return seq + [end-1]


def model_gen(model, text, images, need_bos=True, hd_num=25, max_new_token=2048, beam=3, do_sample=False):
    pt1 = 0
    embeds = []
    im_mask = []
    if images is None:
        images = []
        images_loc = []
    else:
        images = [images]
        images_loc = [0]
    for i, pts in enumerate(images_loc + [len(text)]):
        subtext = text[pt1:pts]
        if need_bos or len(subtext) > 0:
            text_embeds = model.encode_text(
                subtext, add_special_tokens=need_bos)
            embeds.append(text_embeds)
            im_mask.append(torch.zeros(text_embeds.shape[:2]).cuda())
            need_bos = False
        if i < len(images):
            try:
                image = Image.open(images[i]).convert('RGB')
            except:
                image = images[i].convert('RGB')

            image = HD_transform(image, hd_num=hd_num)
            image = model.vis_processor(image).unsqueeze(0).cuda()
            image_embeds = model.encode_img(image)
            print(image_embeds.shape)
            embeds.append(image_embeds)
            im_mask.append(torch.ones(image_embeds.shape[:2]).cuda())
        pt1 = pts
    embeds = torch.cat(embeds, dim=1)
    im_mask = torch.cat(im_mask, dim=1)
    im_mask = im_mask.bool()
    outputs = model.generate(inputs_embeds=embeds, im_mask=im_mask,
                             temperature=1.0, max_new_tokens=max_new_token, num_beams=beam,
                             do_sample=False, repetition_penalty=1.00)

    output_token = outputs[0]
    if output_token[0] == 0 or output_token[0] == 1:
        output_token = output_token[1:]
    output_text = model.tokenizer.decode(
        output_token, add_special_tokens=False)
    output_text = output_text.split('[UNUSED_TOKEN_145]')[0].strip()
    output_text = output_text.split('<|im_end|>')[0].strip()
    return output_text


def img_process(imgs):
    new_w = 0
    new_h = 0
    for im in imgs:
        w, h = im.size
        new_w = max(new_w, w)
        new_h += h + 20
    pad = max(new_w // 4, 100)
    new_w += 20
    new_h += 20
    font = ImageFont.truetype("SimHei.ttf", pad // 5)
    new_img = Image.new('RGB', (new_w + pad, new_h), 'white')
    draw = ImageDraw.Draw(new_img)
    curr_h = 10
    for idx, im in enumerate(imgs):
        w, h = im.size
        new_img.paste(im, (pad, curr_h))
        draw.text((0, curr_h + h // 2),
                  f'<IMAGE {idx}>', font=font, fill='black')
        if idx + 1 < len(imgs):
            draw.line([(0, curr_h + h + 10), (new_w+pad,
                      curr_h + h + 10)], fill='black', width=2)
        curr_h += h + 20
    return new_img


def load_quota_video(vis_path, start=None, end=None):
    vr = VideoReader(vis_path)
    total_frame_num = len(vr)
    fps = vr.get_avg_fps()
    if start is not None:
        assert end is not None
        start_frame = int(start * fps)
        end_frame = min(int(end * fps), total_frame_num)
    else:
        start_frame = 0
        end_frame = total_frame_num
    interval = int(2 * fps)
    frame_idx = list(range(start_frame, end_frame, interval))
    img_array = vr.get_batch(frame_idx).asnumpy()
    num_frm, H, W, _ = img_array.shape
    img_array = img_array.reshape(
        (1, num_frm, img_array.shape[-3], img_array.shape[-2], img_array.shape[-1]))
    clip_imgs = []
    for j in range(num_frm):
        clip_imgs.append(Image.fromarray(img_array[0, j]))
    return clip_imgs


def load_video_segments(vis_path, seg_duration_sec=2.0, frames_per_segment=4):
    """Sample the video into fixed-length segments, each with N dense frames.

    Returns a list of segments; each segment is a list of PIL.Image frames
    sampled uniformly across its `seg_duration_sec` window.
    """
    vr = VideoReader(vis_path)
    total_frame_num = len(vr)
    fps = vr.get_avg_fps()
    video_duration = total_frame_num / fps
    # Include the trailing partial window if it covers >= 50% of a segment,
    # so a 5.8s video still yields 3 segments ([1-2][3-4][5-6]).
    full = int(video_duration // seg_duration_sec)
    remainder = video_duration - full * seg_duration_sec
    num_segments = full + (1 if remainder >= seg_duration_sec * 0.5 else 0)
    num_segments = max(1, num_segments)
    segments = []
    for s in range(num_segments):
        seg_start = s * seg_duration_sec
        seg_end = (s + 1) * seg_duration_sec
        start_f = int(seg_start * fps)
        end_f = min(int(seg_end * fps), total_frame_num) - 1
        if end_f <= start_f:
            end_f = start_f
        idxs = np.linspace(start_f, end_f, num=frames_per_segment).round().astype(int).tolist()
        idxs = [min(max(0, i), total_frame_num - 1) for i in idxs]
        arr = vr.get_batch(idxs).asnumpy()
        frames = [Image.fromarray(arr[j]) for j in range(arr.shape[0])]
        segments.append(frames)
    return segments, num_segments


def compose_segment_grid(frames):
    """Compose a list of 2-4 frames into a single PIL image for model input.

    - 2 frames: vertical stack (matches official pair layout)
    - 3 frames: horizontal strip
    - 4 frames: 2x2 grid
    """
    n = len(frames)
    w, h = frames[0].size
    gap = 20
    if n == 1:
        return frames[0]
    if n == 2:
        canvas = Image.new('RGB', (w, 2 * h + gap), 'white')
        canvas.paste(frames[0], (0, 0))
        canvas.paste(frames[1], (0, h + gap))
        return canvas
    if n == 3:
        canvas = Image.new('RGB', (3 * w + 2 * gap, h), 'white')
        for i, f in enumerate(frames):
            canvas.paste(f, (i * (w + gap), 0))
        return canvas
    # n >= 4 -> 2x2 grid of the first 4
    canvas = Image.new('RGB', (2 * w + gap, 2 * h + gap), 'white')
    canvas.paste(frames[0], (0, 0))
    canvas.paste(frames[1], (w + gap, 0))
    canvas.paste(frames[2], (0, h + gap))
    canvas.paste(frames[3], (w + gap, h + gap))
    return canvas


def resize_image(image_path, max_size=1024):
    with Image.open(image_path) as img:
        width, height = img.size
        if width > max_size or height > max_size:
            if width > height:
                new_width = max_size
                new_height = int(height * (max_size / width))
            else:
                new_height = max_size
                new_width = int(width * (max_size / height))
        else:
            new_width = width
            new_height = height
        resized_img = img.resize((new_width, new_height))
        print(f"resized_img_size: {resized_img.size}")
        return resized_img


def encode_resized_image(image_path, max_size=1024):
    resized_img = resize_image(image_path, max_size)
    try:
        with BytesIO() as buffer:
            resized_img.save(buffer, format="JPEG")
            return base64.b64encode(buffer.getvalue()).decode('utf-8')
    except:
        with BytesIO() as buffer:
            rgb_img = resized_img.convert('RGB')
            rgb_img.save(buffer, format="JPEG")
            return base64.b64encode(buffer.getvalue()).decode('utf-8')


@spaces.GPU(duration=60)
def generate_slidingcaptioning(video_path):
    # Dense sampling: 4 frames per 2s segment so motion-heavy moments are not lost.
    frames_per_segment = 4
    segments, num_segments = load_video_segments(
        video_path, seg_duration_sec=2.0, frames_per_segment=frames_per_segment,
    )
    responses = []
    prior = ""
    for seg_idx in range(num_segments):
        t0 = 1 + seg_idx * 2
        t1 = 2 + seg_idx * 2
        composite = compose_segment_grid(segments[seg_idx])
        if seg_idx == 0:
            q = (
                f"Here are {frames_per_segment} frames sampled from the opening "
                f"[{t0}s-{t1}s] segment of a video. Describe what happens in this "
                "2-second segment in detail."
            )
        else:
            q = (
                f"Here are {frames_per_segment} frames sampled from the "
                f"[{t0}s-{t1}s] segment of a video, describe what happens in "
                f"this 2-second segment. What happened before is: {prior}"
            )
        query = f'[UNUSED_TOKEN_146]user\n{q}[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\n'
        with torch.cuda.amp.autocast():
            response = model_gen(model, query, composite, hd_num=9)
        print(f"[seg {seg_idx} {t0}-{t1}s]", response[:200])
        responses.append(response)
        prior = response
    lines = []
    for i, txt in enumerate(responses):
        t0 = 1 + i * 2
        t1 = 2 + i * 2
        lines.append(f"[{t0}s-{t1}s] {txt.strip()}")
    return "\n\n".join(lines)


@spaces.GPU(duration=60)
def generate_fastcaptioning(video_path):
    q = 'Here are a few key frames of a video, discribe this video in detail.'
    query = f'[UNUSED_TOKEN_146]user\n{q}[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\n'
    imgs = load_quota_video(video_path)
    img = img_process(imgs)
    with torch.cuda.amp.autocast():
        response = model_gen(model, query, img, hd_num=16,
                             do_sample=False, beam=3)
    return response


@spaces.GPU(duration=60)
def generate_promptrecaptioning(text):
    q = f'Translate this brief generation prompt into a detailed caption: {text}'
    query = f'[UNUSED_TOKEN_146]user\n{q}[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\n'
    with torch.cuda.amp.autocast():
        response = model_gen(model, query, None)
    return response


def save_video_to_local(video_path):
    filename = os.path.join('temp', next(
        tempfile._get_candidate_names()) + '.mp4')
    shutil.copyfile(video_path, filename)
    return filename


with gr.Blocks(title='ShareCaptioner-Video', theme=gr.themes.Default(), css=block_css) as demo:
    gr.Markdown(title_markdown)
    state = gr.State()
    state_ = gr.State()
    first_run = gr.State()

    with gr.Row():
        gr.Markdown("### The ShareCaptioner-Video is a Four-in-One exceptional video captioning model with the following capabilities:\n1. Fast captioning, 2. Sliding Captioning, 3. Clip Summarizing, 4. Prompt Re-Captioning")
    with gr.Row():
        gr.Markdown("(THE DEMO OF \"Clip Summarizing\" IS COMING SOON...)")
    with gr.Row():
        with gr.Column(scale=6):
            with gr.Row():
                video = gr.Video(label="Input Video")
            with gr.Row():
                textbox = gr.Textbox(
                    show_label=False, placeholder="Input Text", container=False
                )
            with gr.Row():
                with gr.Column(scale=2, min_width=50):
                    submit_btn_sc = gr.Button(
                        value="Sliding Captioning", variant="primary", interactive=True
                    )
                with gr.Column(scale=2, min_width=50):
                    submit_btn_fc = gr.Button(
                        value="Fast Captioning", variant="primary", interactive=True
                    )
                with gr.Column(scale=2, min_width=50):
                    submit_btn_pr = gr.Button(
                        value="Prompt Re-captioning", variant="primary", interactive=True
                    )
        with gr.Column(scale=4, min_width=200):
            with gr.Row():
                textbox_out = gr.Textbox(
                    show_label=False, placeholder="Output", container=False
                )
    gr.Markdown(learn_more_markdown)

    submit_btn_sc.click(generate_slidingcaptioning, [video], [textbox_out])
    submit_btn_fc.click(generate_fastcaptioning, [video], [textbox_out])
    submit_btn_pr.click(generate_promptrecaptioning, [textbox], [textbox_out])

_server_name = os.environ.get("GRADIO_SERVER_NAME", "0.0.0.0")
_server_port = int(os.environ.get("GRADIO_SERVER_PORT", "7860"))
_share = os.environ.get("GRADIO_SHARE", "false").lower() in ("1", "true", "yes")
# 无桌面/无回环访问时 Gradio 会要求 share=True；无公网分享时用 _frontend=False 跳过检测。
_gradio_frontend = os.environ.get("GRADIO_FRONTEND", "false").lower() in ("1", "true", "yes")
demo.launch(
    server_name=_server_name,
    server_port=_server_port,
    share=_share,
    inbrowser=False,
    show_api=False,
    _frontend=_gradio_frontend,
)
